package Interface;

import Backend.MotorJogoDaVelha;
import javax.swing.*;

public class InterfaceJogo extends javax.swing.JFrame {

    MotorJogoDaVelha motor;
    JButton botoesJogo[];

    public InterfaceJogo()
    {
        initComponents();
        
        //Declara-se novo motor com pontuacao 0 para players
        motor = new MotorJogoDaVelha(new int[]
        {
            0, 0
        });
        
        //Lista dos botões pra facilitar manipulação
        botoesJogo = new JButton[]
        {
            botao0, botao1, botao2, botao3, botao4, botao5, botao6, botao7, botao8
        };
        renderizaBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        botao0 = new javax.swing.JButton();
        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        turnoLabel = new javax.swing.JLabel();
        tituloPlacaLabel = new javax.swing.JLabel();
        placarP1Label = new javax.swing.JLabel();
        placarP2Label = new javax.swing.JLabel();
        restartBotao = new javax.swing.JButton();
        infoBotao = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(263, 164));
        setMinimumSize(new java.awt.Dimension(261, 162));
        setResizable(false);

        botao0.setText("-");
        botao0.setFocusable(false);
        botao0.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        botao1.setText("-");
        botao1.setFocusable(false);
        botao1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        botao2.setText("-");
        botao2.setFocusable(false);
        botao2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        botao3.setText("-");
        botao3.setFocusable(false);
        botao3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        botao4.setText("-");
        botao4.setFocusable(false);
        botao4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        botao5.setText("-");
        botao5.setFocusable(false);
        botao5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        botao6.setText("-");
        botao6.setFocusable(false);
        botao6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        botao7.setText("-");
        botao7.setFocusable(false);
        botao7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        botao8.setText("-");
        botao8.setFocusable(false);
        botao8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoFazJogada(evt);
            }
        });

        turnoLabel.setText("A vez é do player:");

        tituloPlacaLabel.setText("Placar:");

        placarP1Label.setText("X: 0");

        placarP2Label.setText("O: 0");

        restartBotao.setText("Recomeçar");
        restartBotao.setEnabled(false);
        restartBotao.setFocusable(false);
        restartBotao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                restartBotaoActionPerformed(evt);
            }
        });

        infoBotao.setText("Info");
        infoBotao.setFocusable(false);
        infoBotao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                infoBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloPlacaLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(placarP1Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(placarP2Label)))
                                .addGap(17, 17, 17))
                            .addComponent(restartBotao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(infoBotao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(turnoLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turnoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloPlacaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placarP1Label)
                            .addComponent(placarP2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(restartBotao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao0)
                            .addComponent(botao1)
                            .addComponent(botao2))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao3)
                            .addComponent(botao4)
                            .addComponent(botao5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao6)
                            .addComponent(botao7)
                            .addComponent(botao8)
                            .addComponent(infoBotao))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFazJogada(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoFazJogada
    {//GEN-HEADEREND:event_botaoFazJogada
        int i;//Loop pra identificar o index do botão apertado;
        for (i = 0; i < botoesJogo.length; ++i)
        {
            if (evt.getSource().equals(botoesJogo[i]))
            {
                break;
            }
        }

        //Atualizar tabuleiro de acordo com o index e o turno;
        motor.atualizaTabuleiro(i, motor.getPlayerTurno());

        //Atualiza interface
        renderizaBotoes();
        //Teste se jogo terminou ou não
        checaFimDeJogo();


    }//GEN-LAST:event_botaoFazJogada

    private void restartBotaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_restartBotaoActionPerformed
    {//GEN-HEADEREND:event_restartBotaoActionPerformed
        reiniciaJogo();
    }//GEN-LAST:event_restartBotaoActionPerformed

    private void infoBotaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_infoBotaoActionPerformed
    {//GEN-HEADEREND:event_infoBotaoActionPerformed
        //Mensagem de info
        JOptionPane.showMessageDialog(null, "Trabalho feito por:\n"
                + "Kaique Alan G. Santos - RA:120176\n"
                + "Gabriel dos Reis Conceição - RA: 120172\n");
    }//GEN-LAST:event_infoBotaoActionPerformed

    public void reiniciaJogo()
    {
        //Desabilita botão de restart
        restartBotao.setEnabled(false);
        //Reabilita todos botões
        defineEstadoBotoes(true);

        //Re-declara motor, com pontuacao nova
        motor = new MotorJogoDaVelha(motor.getPontuacaoPlayers());

        //Atualiza interface
        renderizaBotoes();
    }

    public void checaFimDeJogo()
    {
        //Caso fim de jogo
        if (motor.fimDeJogo())
        {
            encerraJogo();
        }
    }

    public void defineEstadoBotoes(boolean estado)
    {
        //Para cada botão, muda o estado
        for (JButton aux : botoesJogo)
        {
            aux.setEnabled(estado);
        }

    }

    public void encerraJogo()
    {
        //Desabilita botoes
        defineEstadoBotoes(false);
        //Atualiza texto de turno
        renderizaTurno(true);
        //Atualiza pontos
        motor.atualizaPontuacao();
        //Atuliza pontos interface
        renderizaPontuacao();
        //Ativa botão restart
        restartBotao.setEnabled(true);
    }

    public void renderizaTurno(boolean fimDeJogo)
    {
        //Altera string turno
        
        String turnoTexto;
        
        //Caso seja fim de jogo;
        if(fimDeJogo)turnoTexto = "\"" + motor.getGanhador() + "\" foi ganhador!";
        else turnoTexto = "Quem joga é o player: \"" + motor.getPlayerTurno() + "\"";
        
        turnoLabel.setText(turnoTexto);

    }

    public void renderizaPontuacao()
    {
        //Pega players do motor
        String ps[] = motor.getPlayers();
        //Pega pontuacao players
        int[] pontPlayers = motor.getPontuacaoPlayers();

        //Atualiza textos
        String t1 = ps[0] + ": " + pontPlayers[0];
        placarP1Label.setText(t1);

        String t2 = ps[1] + ": " + pontPlayers[1];
        placarP2Label.setText(t2);
    }

    public void renderizaBotoes()
    {
        //Pega tabuleiro do motor
        String[] tab = motor.getTabuleiro();

        //Pra cada botãoo
        for (int i = 0; i < tab.length; ++i)
        {
            //Se respectivo botão esta ativado
            if (botoesJogo[i].isEnabled())
            {
                //Muda texto para o mesmo do tabuleiro
                botoesJogo[i].setText(tab[i]);

                //Se respectiva celula do tabuleiro não for vazio
                if (!tab[i].equals(MotorJogoDaVelha.charVazio))
                {
                    //Desative o botão respectivo
                    botoesJogo[i].setEnabled(false);
                }
            }
        }
        //Renderiza turno (não final de jogo)
        renderizaTurno(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new InterfaceJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton infoBotao;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel placarP1Label;
    private javax.swing.JLabel placarP2Label;
    private javax.swing.JButton restartBotao;
    private javax.swing.JLabel tituloPlacaLabel;
    private javax.swing.JLabel turnoLabel;
    // End of variables declaration//GEN-END:variables
}
