"""empty message

Revision ID: f2570a6032c2
Revises: 
Create Date: 2018-09-13 02:41:52.965240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2570a6032c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    op.drop_constraint(None, 'acc_assc', type_='foreignkey')
    op.create_foreign_key(None, 'acc_assc', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'acc_assc', type_='foreignkey')
    op.create_foreign_key(None, 'acc_assc', 'histories', ['service_id'], ['id'])
    op.create_table('histories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('veterinarian_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pet_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
