/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CPUEmulador.Visual;

import CPUEmulador.CPU.Register;
import CPUEmulador.Computer;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Kai
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    private Computer computer;
    private JTextField[] decimals;
    private JTextField[] binaries;

    public MainScreen(Computer computer)
    {
        this();
        setComputer(computer);
        
    }

    public MainScreen()
    {
        initComponents();
        
        decimals = new JTextField[]
        {
            DR_d,
            AC_d,
            AR_d,
            IR_d,
            PC_d,
            TR_d
        };

        binaries = new JTextField[]
        {
            DR_b,
            AC_b,
            AR_b,
            IR_b,
            PC_b,
            TR_b
        };
        
    }

    public void setComputer(Computer computer)
    {
        this.computer = computer;
        updateText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        DR_d = new javax.swing.JTextField();
        AC_d = new javax.swing.JTextField();
        AR_d = new javax.swing.JTextField();
        IR_d = new javax.swing.JTextField();
        PC_d = new javax.swing.JTextField();
        TR_d = new javax.swing.JTextField();
        DR_b = new javax.swing.JTextField();
        AC_b = new javax.swing.JTextField();
        AR_b = new javax.swing.JTextField();
        IR_b = new javax.swing.JTextField();
        PC_b = new javax.swing.JTextField();
        TR_b = new javax.swing.JTextField();
        AC_l = new javax.swing.JLabel();
        DR_l = new javax.swing.JLabel();
        AR_l = new javax.swing.JLabel();
        IR_l = new javax.swing.JLabel();
        PC_l = new javax.swing.JLabel();
        TR_l = new javax.swing.JLabel();
        step = new javax.swing.JButton();
        microStep = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        memory = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        code = new javax.swing.JTextArea();
        loadAsm = new javax.swing.JButton();
        loadAsm1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Von Neumman Aplicado");
        setResizable(false);

        DR_d.setText("0");

        AC_d.setText("0");
        AC_d.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AC_dActionPerformed(evt);
            }
        });

        AR_d.setText("0");

        IR_d.setText("0");

        PC_d.setText("0");
        PC_d.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PC_dActionPerformed(evt);
            }
        });

        TR_d.setText("0");

        DR_b.setText("0");

        AC_b.setText("0");

        AR_b.setText("0");

        IR_b.setText("0");

        PC_b.setText("0");

        TR_b.setText("0");

        AC_l.setText("AC");

        DR_l.setText("DR");

        AR_l.setText("AR");

        IR_l.setText("IR");

        PC_l.setText("PC");

        TR_l.setText("TR");

        step.setText("Step");
        step.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stepActionPerformed(evt);
            }
        });

        microStep.setText("MicroStep");
        microStep.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                microStepActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(memory);

        code.setColumns(12);
        jScrollPane1.setViewportView(code);

        loadAsm.setText("LoadAssembly");
        loadAsm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadAsmActionPerformed(evt);
            }
        });

        loadAsm1.setText("Sobre");
        loadAsm1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadAsm1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AC_l)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AC_d, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DR_l)
                                    .addComponent(AR_l)
                                    .addComponent(IR_l))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AR_d, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(DR_d, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IR_d))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DR_b)
                            .addComponent(AR_b)
                            .addComponent(IR_b)
                            .addComponent(AC_b))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PC_l)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PC_d, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TR_l)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TR_d, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TR_b)
                                    .addComponent(PC_b, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addComponent(step)
                                .addGap(18, 18, 18)
                                .addComponent(microStep))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(loadAsm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loadAsm1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loadAsm)
                            .addComponent(loadAsm1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TR_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TR_l))
                            .addComponent(TR_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PC_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PC_l))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(step)
                                .addComponent(microStep)
                                .addComponent(PC_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DR_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DR_l)
                            .addComponent(DR_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AR_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AR_l)
                            .addComponent(AR_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IR_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IR_l)
                            .addComponent(IR_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AC_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AC_l)
                            .addComponent(AC_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AC_dActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AC_dActionPerformed
    {//GEN-HEADEREND:event_AC_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AC_dActionPerformed

    private void stepActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stepActionPerformed
    {//GEN-HEADEREND:event_stepActionPerformed
        computer.getProcessor().step();

        updateText();
    }//GEN-LAST:event_stepActionPerformed

    private void microStepActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_microStepActionPerformed
    {//GEN-HEADEREND:event_microStepActionPerformed
    
        computer.getProcessor().ustep();
        step.setEnabled(computer.getProcessor().isValidStep());
        updateText();
    }//GEN-LAST:event_microStepActionPerformed

    private void loadAsmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadAsmActionPerformed
    {//GEN-HEADEREND:event_loadAsmActionPerformed
        computer = new Computer(code.getText());
        updateText();
    }//GEN-LAST:event_loadAsmActionPerformed

    private void PC_dActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PC_dActionPerformed
    {//GEN-HEADEREND:event_PC_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PC_dActionPerformed

    private void loadAsm1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadAsm1ActionPerformed
    {//GEN-HEADEREND:event_loadAsm1ActionPerformed
        JOptionPane.showMessageDialog(null, "Feitos por:\n Kaique Alan Gualter dos Santos RA:120176\n Gabriel dos Reis Conceição RA:120172","Créditos",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_loadAsm1ActionPerformed

    void updateText()
    {
        Register[] registers = computer.getProcessor().getRegisters();
        
        for (int i = 0; i < decimals.length; ++i)
        {            
            decimals[i].setText(registers[i].getValue() + "");
            binaries[i].setText(registers[i].getBinaryData());
        }
        
        code.setText(computer.getAssembly());
        memory.setListData(computer.getMemory().getLines());
        memory.setSelectedIndex(computer.getProcessor().getPC().getValue());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AC_b;
    private javax.swing.JTextField AC_d;
    private javax.swing.JLabel AC_l;
    private javax.swing.JTextField AR_b;
    private javax.swing.JTextField AR_d;
    private javax.swing.JLabel AR_l;
    private javax.swing.JTextField DR_b;
    private javax.swing.JTextField DR_d;
    private javax.swing.JLabel DR_l;
    private javax.swing.JTextField IR_b;
    private javax.swing.JTextField IR_d;
    private javax.swing.JLabel IR_l;
    private javax.swing.JTextField PC_b;
    private javax.swing.JTextField PC_d;
    private javax.swing.JLabel PC_l;
    private javax.swing.JTextField TR_b;
    private javax.swing.JTextField TR_d;
    private javax.swing.JLabel TR_l;
    private javax.swing.JTextArea code;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadAsm;
    private javax.swing.JButton loadAsm1;
    private javax.swing.JList<String> memory;
    private javax.swing.JButton microStep;
    private javax.swing.JButton step;
    // End of variables declaration//GEN-END:variables
}
